dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
dependency_overrides:
  connectivity_plus:
    git:
      path: packages/connectivity_plus/connectivity_plus
      url: https://gitee.com/openharmony-sig/flutter_plus_plugins.git
  webview_flutter:
    git:
      path: packages/webview_flutter/webview_flutter
      url: https://gitee.com/openharmony-sig/flutter_packages.git
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=3.4.0 <4.0.0'
flutter:
  uses-material-design: true
name: webapp
publish_to: none
version: 1.0.0+1
